#!/usr/bin/env python3
"""名前・判定・メモを保存できるブラウザ用編集HTMLを生成する。"""
from __future__ import annotations
import base64, json, html
from pathlib import Path

ROOT=Path(__file__).resolve().parent
MASTER=ROOT/'step2_dedup'/'monster_master_330.json'
SPRITES=ROOT/'step1_normalized'/'sprites'
OUT=ROOT/'monster_editor.html'

def uri(p:Path)->str:
    return 'data:image/png;base64,'+base64.b64encode(p.read_bytes()).decode()

def main():
    rows=json.loads(MASTER.read_text(encoding='utf-8'))
    for r in rows: r['image']=uri(SPRITES/f"{r['id']}.png")
    payload=json.dumps(rows,ensure_ascii=False,separators=(',',':')).replace('</','<\\/')
    types=['','スライム','ドラゴン','けもの','鳥翼','自然','むし','水棲','物質','不死','幻魔']
    type_options=''.join(f'<option>{html.escape(t)}</option>' for t in types if t)
    doc=f'''<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>モンスター編集台帳</title><style>
*{{box-sizing:border-box}}body{{margin:0;background:#0e1422;color:#eef3fb;font-family:system-ui,sans-serif}}header{{position:sticky;top:0;z-index:4;background:#151e31f5;border-bottom:1px solid #40516f;padding:12px 14px;backdrop-filter:blur(10px)}}h1{{font-size:19px;margin:0 0 6px}}.notice{{font-size:12px;color:#ffdf9a;margin:3px 0 9px}}.toolbar{{display:flex;gap:7px;flex-wrap:wrap}}button,input,select,textarea{{background:#202c45;color:#fff;border:1px solid #526887;border-radius:6px;padding:7px 9px}}button{{cursor:pointer}}.primary{{background:#267552;border-color:#70d3a7}}main{{padding:14px;max-width:1450px;margin:auto}}.grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(245px,1fr));gap:11px}}.card{{background:#171f32;border:1px solid #34415c;border-radius:11px;overflow:hidden}}.card.drop{{opacity:.52}}.card.hold{{border-color:#bd923d}}.card img{{display:block;width:100%;height:190px;object-fit:contain;image-rendering:pixelated;background:repeating-conic-gradient(#20283a 0 25%,#182033 0 50%) 0/20px 20px}}.body{{padding:9px}}.small{{font-size:12px;color:#b6c4d9}}.body input.name{{width:100%;font-size:15px;margin:5px 0}}.body textarea{{width:100%;height:42px;resize:vertical;margin-top:5px;font-size:12px}}.tag{{display:inline-block;font-size:11px;background:#2a3958;border-radius:999px;padding:3px 7px;margin:2px}}.count{{color:#9bdcff;font-size:13px}}p{{font-size:13px;color:#c9d3e3;margin:5px 0;min-height:34px}}.empty{{padding:28px;color:#b6c4d9}}
</style></head><body><header><h1>モンスター編集台帳</h1><div class="notice">名前を変えたら自動保存されます。保存先はこの端末のブラウザ内です。確実に残すには「JSON書き出し」を押してください。</div><div class="toolbar"><input id="q" placeholder="ID・名前・説明を検索"><select id="status"><option value="">全判定</option><option>採用</option><option>保留</option><option>除外候補</option></select><select id="type"><option value="">全タイプ</option>{type_options}</select><select id="tier"><option value="">全階級</option><option>下位</option><option>中位</option><option>上位</option><option>最上位</option></select><button class="primary" id="save">今すぐ保存</button><button id="export">JSON書き出し</button><button id="importBtn">JSON読み込み</button><input id="file" type="file" accept="application/json" hidden><button id="reset">初期値に戻す</button><span id="count" class="count"></span></div></header><main><div id="grid" class="grid"></div></main><script>
const baseRows={payload};const key='monster_editor_v3';let rows=baseRows;try{{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved){{for(const r of rows){{if(saved[r.id]){{r.working_name=saved[r.id].working_name??r.working_name;r.status=saved[r.id].status??r.status;r.memo=saved[r.id].memo??''}}}}}}}}catch(e){{}}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]));const save=()=>{{const out={{}};rows.forEach(r=>out[r.id]={{working_name:r.working_name,status:r.status,memo:r.memo||''}});localStorage.setItem(key,JSON.stringify(out));document.querySelector('#count').textContent='変更を保存しました';}};
function render(){{const q=document.querySelector('#q').value.trim().toLowerCase(),st=document.querySelector('#status').value,ty=document.querySelector('#type').value,ti=document.querySelector('#tier').value;const f=rows.filter(r=>(!st||r.status===st)&&(!ty||r.type===ty)&&(!ti||r.tier===ti)&&(!q||[r.id,r.working_name,r.description,r.memo||''].join(' ').toLowerCase().includes(q)));document.querySelector('#count').textContent=`表示 ${{f.length}} / 330体`;document.querySelector('#grid').innerHTML=f.length?f.map(r=>`<article class="card ${{r.status==='除外候補'?'drop':r.status==='保留'?'hold':''}}"><img src="${{r.image}}" alt="${{r.id}}"><div class="body"><div class="small">${{r.id}} ・ ${{r.tier}}</div><input class="name" data-id="${{r.id}}" value="${{esc(r.working_name)}}" maxlength="8"><p>${{esc(r.description)}}</p><select class="decision" data-id="${{r.id}}"><option ${{r.status==='採用'?'selected':''}}>採用</option><option ${{r.status==='保留'?'selected':''}}>保留</option><option ${{r.status==='除外候補'?'selected':''}}>除外候補</option></select><span class="tag">${{r.type}}</span>${{r.secondary_types.map(x=>`<span class="tag">副:${{x}}</span>`).join('')}}<textarea class="memo" data-id="${{r.id}}" placeholder="メモ（任意）">${{esc(r.memo||'')}}</textarea></div></article>`).join(''):'<div class="empty">該当するモンスターはいません。</div>';document.querySelectorAll('.name').forEach(x=>x.oninput=()=>{{rows.find(r=>r.id===x.dataset.id).working_name=x.value.slice(0,8);save()}});document.querySelectorAll('.decision').forEach(x=>x.onchange=()=>{{rows.find(r=>r.id===x.dataset.id).status=x.value;save();render()}});document.querySelectorAll('.memo').forEach(x=>x.oninput=()=>{{rows.find(r=>r.id===x.dataset.id).memo=x.value;save()}})}}
['q','status','type','tier'].forEach(id=>document.querySelector('#'+id).addEventListener('input',render));document.querySelector('#save').onclick=save;document.querySelector('#reset').onclick=()=>{{if(confirm('この端末に保存した変更を消して初期値へ戻しますか？')){{localStorage.removeItem(key);location.reload()}}}};document.querySelector('#export').onclick=()=>{{save();const blob=new Blob([JSON.stringify(rows.map(r=>({{id:r.id,working_name:r.working_name,status:r.status,memo:r.memo||''}})),null,2)],{{type:'application/json'}});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='monster_edits.json';a.click()}};document.querySelector('#importBtn').onclick=()=>document.querySelector('#file').click();document.querySelector('#file').onchange=e=>{{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{{const changes=JSON.parse(reader.result);for(const c of changes){{const r=rows.find(r=>r.id===c.id);if(r){{r.working_name=c.working_name??r.working_name;r.status=c.status??r.status;r.memo=c.memo??r.memo}}}}save();render()}};reader.readAsText(f)}};render();
</script></body></html>'''
    OUT.write_text(doc,encoding='utf-8');print(OUT,OUT.stat().st_size)

if __name__=='__main__':main()
