#!/usr/bin/env python3
"""相対リンクなしで開ける、プロジェクト確認用の単体HTMLを作る。"""
from __future__ import annotations
import base64, json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
MASTER = ROOT / "step2_dedup" / "monster_master_330.json"
SPRITES = ROOT / "step1_normalized" / "sprites"
OVERVIEW = ROOT / "step1_normalized" / "qa" / "overview.jpg"
DEDUP = ROOT / "step2_dedup" / "dedup_review.jpg"
OUT = ROOT / "monster_project_standalone.html"

def data_uri(path: Path) -> str:
    mime = "image/jpeg" if path.suffix.lower() in {".jpg", ".jpeg"} else "image/png"
    return f"data:{mime};base64," + base64.b64encode(path.read_bytes()).decode()

def main() -> None:
    rows = json.loads(MASTER.read_text(encoding="utf-8"))
    for row in rows:
        row["image"] = data_uri(SPRITES / f"{row['id']}.png")
    overview = data_uri(OVERVIEW)
    dedup = data_uri(DEDUP)
    payload = json.dumps(rows, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")
    html = f'''<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>モンスタープロジェクト 完結版</title><style>
*{{box-sizing:border-box}}body{{margin:0;background:#0d1320;color:#edf2fb;font-family:system-ui,sans-serif}}header{{position:sticky;top:0;z-index:5;background:#151d30f2;border-bottom:1px solid #34415c;padding:13px 16px;backdrop-filter:blur(12px)}}h1{{font-size:20px;margin:0 0 10px}}button,input,select{{background:#202c45;color:#fff;border:1px solid #4b5d7d;border-radius:7px;padding:8px 10px}}button{{cursor:pointer}}nav{{display:flex;gap:7px;flex-wrap:wrap}}nav button.active{{background:#29709b;border-color:#8ddcff}}main{{padding:16px;max-width:1400px;margin:auto}}.tab{{display:none}}.tab.active{{display:block}}.hero{{width:100%;max-height:680px;object-fit:contain;object-position:top;background:#101626;border:1px solid #34415c;border-radius:12px;image-rendering:auto}}.stats,.cards{{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:10px;margin:14px 0}}.stat,.panel,.card{{background:#171f32;border:1px solid #34415c;border-radius:12px;padding:13px}}.stat b{{display:block;font-size:25px;color:#8fd8ff}}.muted,.small{{color:#b9c6db;font-size:13px}}.toolbar{{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}}.grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:12px}}.monster{{background:#171f32;border:1px solid #34415c;border-radius:12px;overflow:hidden}}.monster[data-status="除外候補"]{{opacity:.52}}.monster[data-status="保留"]{{border-color:#bf9237}}.pic{{height:210px;display:grid;place-items:center;background:repeating-conic-gradient(#20283a 0 25%,#182033 0 50%) 0/22px 22px}}.pic img{{width:205px;height:205px;object-fit:contain;image-rendering:pixelated}}.body{{padding:10px}}.body h3{{font-size:16px;margin:4px 0}}.tag{{display:inline-block;font-size:11px;background:#2a3958;border-radius:999px;padding:3px 7px;margin:2px}}.keep{{background:#1d684f}}.hold{{background:#89651e}}.drop{{background:#7b343d}}.compare{{width:100%;image-rendering:auto;border-radius:10px;border:1px solid #34415c}}table{{width:100%;border-collapse:collapse;font-size:13px}}th,td{{border-bottom:1px solid #34415c;text-align:left;padding:8px;vertical-align:top}}th{{color:#8fd8ff;position:sticky;top:102px;background:#171f32}}.recipe{{margin:7px 0;padding:10px;border-left:3px solid #5db5e4;background:#1a263b}}.recipe b{{color:#8fd8ff}}@media(max-width:600px){{th,td{{font-size:12px;padding:6px}}}}
</style></head><body><header><h1>モンスタープロジェクト（単体完結版）</h1><nav><button class="tabbtn active" data-tab="home">概要</button><button class="tabbtn" data-tab="catalog">330体台帳</button><button class="tabbtn" data-tab="dedup">重複比較</button><button class="tabbtn" data-tab="fusion">合体設計</button></nav></header><main>
<section id="home" class="tab active"><div class="stats" id="stats"></div><div class="panel"><h2>固定画像仕様</h2><p class="muted">全シート1800×1500px、6列×5段、1マス300×300px。全330体を同一座標で切り抜けます。元画像は未削除です。</p></div><img class="hero" src="{overview}" alt="330体一覧"></section>
<section id="catalog" class="tab"><div class="toolbar"><input id="q" placeholder="ID・名前・説明を検索"><select id="st"><option value="">全状態</option><option>採用</option><option>保留</option><option>除外候補</option></select><select id="ty"><option value="">全タイプ</option>{''.join(f'<option>{t}</option>' for t in ['スライム','ドラゴン','けもの','鳥翼','自然','むし','水棲','物質','不死','幻魔'])}</select><select id="ti"><option value="">全階級</option><option>下位</option><option>中位</option><option>上位</option><option>最上位</option></select><button id="save">変更を保存</button><button id="reset">初期値に戻す</button><button id="export">変更を書き出す</button><span class="muted" id="count"></span></div><div class="grid" id="grid"></div></section>
<section id="dedup" class="tab"><div class="panel"><h2>重複候補18グループ</h2><p class="muted">代表案をKEEP、近い案をDROP?として表示しています。DROP?は削除済みではなく、最終判断までの候補です。</p><img class="compare" src="{dedup}" alt="重複候補比較"></div></section>
<section id="fusion" class="tab"><div class="panel"><h2>合体設計 v0.1</h2><p class="muted">血統側のタイプを結果の主タイプとし、相手側の要素を外見・副タグ・耐性・特技継承へ加える方針です。能力値は未接続です。</p><div id="types" class="cards"></div><h3>固定合体 試作30件</h3><div id="recipes"></div></div></section>
</main><script>
const rows={payload};const saveKey='monster_project_master_v2';try{{const saved=JSON.parse(localStorage.getItem(saveKey)||'null');if(saved){{for(const r of rows){{const s=saved[r.id];if(s){{if(s.working_name)r.working_name=s.working_name;if(s.status)r.status=s.status}}}}}}}}catch(e){{}}
const buttons=[...document.querySelectorAll('.tabbtn')];buttons.forEach(b=>b.onclick=()=>{{buttons.forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.id===b.dataset.tab));if(b.dataset.tab==='catalog')render();}});
const esc=s=>String(s).replace(/[&<>"']/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]));
function render(){{const q=document.querySelector('#q').value.toLowerCase().trim(),st=document.querySelector('#st').value,ty=document.querySelector('#ty').value,ti=document.querySelector('#ti').value;const f=rows.filter(r=>(!st||r.status===st)&&(!ty||r.type===ty)&&(!ti||r.tier===ti)&&(!q||[r.id,r.working_name,r.description,r.dedup_reason].join(' ').toLowerCase().includes(q)));document.querySelector('#count').textContent=`表示 ${{f.length}} / 330体`;document.querySelector('#grid').innerHTML=f.map(r=>`<article class="monster" data-status="${{r.status}}"><div class="pic"><img src="${{r.image}}"></div><div class="body"><span class="small">${{r.id}} · ${{r.tier}}</span><h3><input class="editname" data-id="${{r.id}}" value="${{esc(r.working_name)}}" maxlength="8" style="width:100%;background:#111a2b;color:#fff;border:1px solid #465979;border-radius:5px;padding:5px"></h3><p class="small">${{esc(r.description)}}</p><select class="editstatus" data-id="${{r.id}}"><option ${{r.status==='採用'?'selected':''}}>採用</option><option ${{r.status==='保留'?'selected':''}}>保留</option><option ${{r.status==='除外候補'?'selected':''}}>除外候補</option></select><span class="tag">${{r.type}}</span>${{r.secondary_types.map(x=>`<span class="tag">副:${{x}}</span>`).join('')}}<p class="small">${{esc(r.dedup_reason)}}</p></div></article>`).join('');document.querySelectorAll('.editname').forEach(x=>x.onchange=()=>{{const r=rows.find(r=>r.id===x.dataset.id);r.working_name=x.value.slice(0,8)}});document.querySelectorAll('.editstatus').forEach(x=>x.onchange=()=>{{const r=rows.find(r=>r.id===x.dataset.id);r.status=x.value;render()}})}}
['q','st','ty','ti'].forEach(id=>document.querySelector('#'+id).addEventListener('input',render));document.querySelector('#save').onclick=()=>{{const out={{}};rows.forEach(r=>out[r.id]={{working_name:r.working_name,status:r.status}});localStorage.setItem(saveKey,JSON.stringify(out));alert('この端末に保存しました');}};document.querySelector('#reset').onclick=()=>{{localStorage.removeItem(saveKey);location.reload()}};document.querySelector('#export').onclick=()=>{{const body=JSON.stringify(rows.map(r=>({{id:r.id,working_name:r.working_name,status:r.status}})),null,2);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{{type:'application/json'}}));a.download='monster_changes.json';a.click()}};
const stCount={{採用:rows.filter(r=>r.status==='採用').length,保留:rows.filter(r=>r.status==='保留').length,除外候補:rows.filter(r=>r.status==='除外候補').length}};document.querySelector('#stats').innerHTML=`<div class="stat"><b>330</b>登録画像</div><div class="stat"><b>${{stCount.採用}}</b>採用</div><div class="stat"><b>${{stCount.保留}}</b>保留</div><div class="stat"><b>${{stCount.除外候補}}</b>除外候補</div><div class="stat"><b>10</b>タイプ</div>`;
const typeOrder=['スライム','ドラゴン','けもの','鳥翼','自然','むし','水棲','物質','不死','幻魔'];document.querySelector('#types').innerHTML=typeOrder.map(t=>`<div class="stat"><b>${{rows.filter(r=>r.status!=='除外候補'&&r.type===t).length}}</b>${{t}}</div>`).join('');
const recipes=[['F001','U2-03 + U2-10','U4-06','苔岩の体へ火精の核を入れ、溶岩巨像を作る'],['F002','U2-09 + U2-10','U4-13','甲羅へ火山性を定着させる'],['F003','U1-16 + U2-22','U4-19','森の子ジカへ星精の加護を与える'],['F004','U2-11 + U2-10','U4-22','黒い鳥へ火精の核を継承する'],['F005','U1-30 + U3-17 + G1-21','U4-21','水竜へ魚の適応と磁性装甲を加える'],['F006','U1-08 + U5-29','U4-23','小ガイコツへ死神の呪力を凝縮する'],['F007','U1-26 + U5-22','U4-24','捕食器官と巨樹の生命力を固定する'],['F008','U2-04 + U2-22','U5-11','氷兎へ星月の性質を混ぜる'],['F009','U2-14 + G1-17','U5-15','旅キノコへ音の器官を加える'],['F010','U1-09 + U1-03','U5-18','採掘本能と結晶甲殻を合わせる'],['F011','G1-08 + G2-12','G3-02','器の体へ蒸気生命を宿す'],['F012','G1-09 + G1-21 + G2-06','G3-30','時計・磁力・天体指向を統合する'],['F013','G1-10 + G1-29','G3-09','収納ミミックを旅行かばん化する'],['F014','G1-06 + G1-22','G3-13','ぜんまい人形を戦闘用にする'],['F015','G1-18 + G1-30','G3-01','音の道具とボタンを蛇腹装甲へまとめる'],['F016','G3-30 + G3-17 + G2-05','G5-24','中位方位機構へ小世界とオーロラ動力を組み込み、無限方位盤へ昇華する'],['F017','G3-28 + G3-24','G4-10','鏡霊を騎士の血統へ封じる'],['F018','G3-03 + G3-14 + G2-01','G4-08','音盤・多脚・影から巨大演奏魔を作る'],['F019','G3-11 + G3-22 + G2-06','G4-09','風力炉へ隕石核を落とし込む'],['F020','G3-20 + G3-18','G4-22','二つの都市設備を遊園地を背負う巨像へ拡張する'],['F021','G4-02 + G5-24','G5-16','宮殿時計と無限方位盤を世界時計へ統合する'],['F022','G4-10 + G4-23','G5-11','鏡迷宮へ月観測の聖性を加える'],['F023','G4-12 + G4-30','G5-19','黒穴魔術と異次元門を固定する'],['F024','G4-28 + G4-30','G5-17','虹大聖堂を星雲化する'],['F025','G4-09 + G4-06','G5-20','隕石炉と黒曜石の音楽箱を星鍛造炉へ昇華する'],['F026','G4-16 + G4-26','G5-29','操り王へ多数の王権を集める'],['F027','G4-03 + G4-17','G5-12','日食の支配力と賭けの魔性をまとめる'],['F028','G4-15 + G4-23','G5-15','光の翼と月観測を天球神へ昇華する'],['F029','G4-01 + G4-19 + G4-24','G5-06','三種の巨大な響きを守護者へ束ねる'],['F030','G4-16 + G4-04 + G4-30','G5-27','人形劇・幽霊船・異界門から夢劇場を成立させる']];document.querySelector('#recipes').innerHTML=recipes.map(r=>`<div class="recipe"><b>${{r[0]}}</b>　${{r[1]}}　→　<b>${{r[2]}}</b><br><span class="small">${{r[3]}}</span></div>`).join('');
</script></body></html>'''
    OUT.write_text(html, encoding="utf-8")
    print(OUT, OUT.stat().st_size)

if __name__ == "__main__": main()
